### ISSUE TITLE
Crash on world map (1.1.2)

### ISSUE THREAD

**Issue by williethewolf** [R-Vaccari/bannerlord-banner-kings#101]
**Describe the bug**
Crashes on world map. It was fine for like an hour. 
Solo run. no army. Couple of prisoners. 4 horses.

**Mod Version**
1.2.7.1

**Crash Report**
Outer exception callstack: 
   at TaleWorlds.CampaignSystem.GameComponents.DefaultPartyWageModel.GetTotalWage(MobileParty mobileParty, Boolean includeDescriptions)
   at BannerKings.Models.Vanilla.BKPartyWageModel.GetTotalWage(MobileParty mobileParty, Boolean includeDescriptions)
   at TaleWorlds.CampaignSystem.Party.MobileParty.get_TotalWage_Patch1(MobileParty this)
   at TaleWorlds.CampaignSystem.Party.MobileParty.IsWageLimitExceeded()
   at TaleWorlds.CampaignSystem.CampaignBehaviors.DesertionCampaignBehavior.PartiesCheckDesertionDueToPartySizeExceedsPaymentRatio(MobileParty mobileParty, TroopRoster& desertedTroopList)
   at TaleWorlds.CampaignSystem.CampaignBehaviors.DesertionCampaignBehavior.DailyTickParty(MobileParty mobileParty)
   at TaleWorlds.CampaignSystem.MbEvent`1.InvokeList(EventHandlerRec`1 list, T t)
   at TaleWorlds.CampaignSystem.CampaignEvents.DailyTickParty(MobileParty mobileParty)
   at TaleWorlds.CampaignSystem.CampaignEventDispatcher.DailyTickParty(MobileParty mobileParty)
   at TaleWorlds.CampaignSystem.CampaignPeriodicEventManager.PeriodicTicker`1.PeriodicTickSome(Double timeUnitsElapsed)
   at TaleWorlds.CampaignSystem.CampaignPeriodicEventManager.PeriodicDailyTick()
   at TaleWorlds.CampaignSystem.CampaignPeriodicEventManager.TickPeriodicEvents()
   at TaleWorlds.CampaignSystem.Campaign.Tick()
   at TaleWorlds.CampaignSystem.GameState.MapState.OnMapModeTick(Single dt)
   at TaleWorlds.CampaignSystem.GameState.MapState.OnTick(Single dt)
   at TaleWorlds.Core.GameStateManager.OnTick(Single dt)
   at TaleWorlds.Core.Game.OnTick(Single dt)
   at TaleWorlds.Core.GameManagerBase.OnTick(Single dt)
   at TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch1(Module this, Single dt).

**Comment by UNOwenWasMe** [comment]
I feel like the gold change and wages functions are a little messed up at the moment.
In my current game my troop wages aren't actually counted in the "daily gold change" message, even though the ACTUAL change is still correct (which means I actually get a lot less money than what is shown in the message)
I have experienced a crash before where I saw those same wage functions appear in the stack, but I'm no programmer so the only thing I have is intuitive speculation.
The only thing I can say is that there's /something/ funky going on with the way the wages are calculated

**Comment by UNOwenWasMe** [comment]
Well, what do you know, I'm also having a similar issue right now
It crashes always on the exact same time of day, probably on the daily gold update tick
Posting crash report here, seems like it might be a similar issue so I'm not opening another thread

Exception information
Type: System.Reflection.TargetInvocationException
Message: Exception has been thrown by the target of an invocation.
Source: mscorlib
CallStack:

    at object RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor)
    at object System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(object obj, object[] parameters, object[] arguments)
    at object System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
    at object System.Reflection.MethodBase.Invoke(object obj, object[] parameters)
    at bool BannerKings.Behaviours.Patches.ClanFinancesPatches.PartyExpensesPrefix(Clan clan, ref ExplainedNumber goldChange, bool applyWithdrawals, bool includeDetails) in C:/Users/Rodrigo/source/repos/bannerlord-banner-kings/BannerKings/Behaviours/BKClanBehavior.cs:line 1315
    at void TaleWorlds.CampaignSystem.GameComponents.DefaultClanFinanceModel.AddExpensesFromPartiesAndGarrisons_Patch1(DefaultClanFinanceModel this, Clan clan, ref ExplainedNumber goldChange, bool applyWithdrawals, bool includeDetails)
    at void TaleWorlds.CampaignSystem.GameComponents.DefaultClanFinanceModel.CalculateClanExpensesInternal(Clan clan, ref ExplainedNumber goldChange, bool applyWithdrawals, bool includeDetails)
    at ExplainedNumber TaleWorlds.CampaignSystem.GameComponents.DefaultClanFinanceModel.CalculateClanGoldChange(Clan clan, bool includeDescriptions, bool applyWithdrawals, bool includeDetails)
    at ExplainedNumber BannerKings.Models.Vanilla.BKClanFinanceModel.CalculateClanGoldChange(Clan clan, bool includeDescriptions, bool applyWithdrawals, bool includeDetails) in C:/Users/Rodrigo/source/repos/bannerlord-banner-kings/BannerKings/Models/Vanilla/BKClanFinanceModel.cs:line 85
    at void TaleWorlds.CampaignSystem.CampaignBehaviors.ClanVariablesCampaignBehavior.DailyTickClan(Clan clan)
    at void TaleWorlds.CampaignSystem.MbEvent.InvokeList(EventHandlerRec list, T t)
    at void TaleWorlds.CampaignSystem.CampaignEvents.DailyTickClan(Clan clan)
    at void TaleWorlds.CampaignSystem.CampaignEventDispatcher.DailyTickClan(Clan clan)
    at void TaleWorlds.CampaignSystem.CampaignPeriodicEventManager+PeriodicTicker.PeriodicTickSome(double timeUnitsElapsed)
    at void TaleWorlds.CampaignSystem.CampaignPeriodicEventManager.PeriodicDailyTick()
    at void TaleWorlds.CampaignSystem.CampaignPeriodicEventManager.TickPeriodicEvents()
    at void TaleWorlds.CampaignSystem.Campaign.Tick()
    at void TaleWorlds.CampaignSystem.GameState.MapState.OnMapModeTick(float dt)
    at void TaleWorlds.CampaignSystem.GameState.MapState.OnTick(float dt)
    at void TaleWorlds.Core.GameStateManager.OnTick(float dt)
    at void TaleWorlds.Core.Game.OnTick(float dt)
    at void TaleWorlds.Core.GameManagerBase.OnTick(float dt)
    at void TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch1(Module this, float dt)

Inner Exception information
Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: TaleWorlds.CampaignSystem
CallStack:

    at ExplainedNumber TaleWorlds.CampaignSystem.GameComponents.DefaultPartyWageModel.GetTotalWage(MobileParty mobileParty, bool includeDescriptions)
    at ExplainedNumber BannerKings.Models.Vanilla.BKPartyWageModel.GetTotalWage(MobileParty mobileParty, bool includeDescriptions) in C:/Users/Rodrigo/source/repos/bannerlord-banner-kings/BannerKings/Models/Vanilla/BKPartyWageModel.cs:line 36
    at int TaleWorlds.CampaignSystem.Party.MobileParty.get_TotalWage()
    at int TaleWorlds.CampaignSystem.GameComponents.DefaultClanFinanceModel.CalculatePartyWage(MobileParty mobileParty, int budget, bool applyWithdrawals)
