### ISSUE TITLE
CTD when castle is given after capture

### ISSUE THREAD

**Issue by iEssence** [R-Vaccari/bannerlord-banner-kings#58]
Playing as battania, on several occassions, different saves, sturgian castle and western empire castle (separate saves) 1.0.0 to 1.0.2, when the castle is "handed out"(i think) a day after capture, game crashes. (Other NPC castles in other kingdoms, unrelated to Player had been captured fine before. Possible Battania/player issue?).
All instances happened when serving as a soldier in the army that captured it, with Serve As a Soldier mod, involved modules only list Banner Kings however, but worth to mention it, however it crashes even if army is abandoned and AI takes it themselves, and the Serve mod is uninstalled before. Tried with several versions of Banner Kings, having Banner kings early, and Last in load orders.

Here are 2 of the crash reports with regular exception window
https://report.butr.link/0F9C7E.html :: https://report.butr.link/C3C966.html

Copy of the callstack of better exception

------

Inner exception callstack:
No inner exception was thrown
Outer exception callstack:
   at TaleWorlds.CampaignSystem.GameComponents.DefaultSettlementValueModel.CalculateSettlementValueForFaction(Settlement settlement, IFaction faction)
   at BannerKings.Models.Vanilla.BKSettlementValueModel.CalculateSettlementValueForFaction(Settlement settlement, IFaction faction) in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Models\Vanilla\BKSettlementValueModel.cs:line 12
   at TaleWorlds.CampaignSystem.Election.SettlementClaimantDecision.CalculateMeritOfOutcome_Patch1(SettlementClaimantDecision this, DecisionOutcome candidateOutcome)
   at TaleWorlds.CampaignSystem.Election.KingdomDecision.NarrowDownCandidates(List`1 initialCandidates, Int32 maxCandidateCount)
   at TaleWorlds.CampaignSystem.Election.KingdomElection.Setup()
   at TaleWorlds.CampaignSystem.Kingdom.AddDecision(KingdomDecision kingdomDecision, Boolean ignoreInfluenceCost)
   at BannerKings.Behaviours.BKTitleBehavior.OnDailyTickSettlement(Settlement settlement) in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Behaviours\BKTitleBehavior.cs:line 326
   at TaleWorlds.CampaignSystem.MbEvent`1.InvokeList(EventHandlerRec`1 list, T t)
   at TaleWorlds.CampaignSystem.CampaignEvents.DailyTickSettlement(Settlement settlement)
   at TaleWorlds.CampaignSystem.CampaignEventDispatcher.DailyTickSettlement(Settlement settlement)
   at TaleWorlds.CampaignSystem.CampaignPeriodicEventManager.PeriodicTicker`1.PeriodicTickSome(Double timeUnitsElapsed)
   at TaleWorlds.CampaignSystem.CampaignPeriodicEventManager.PeriodicDailyTick()
   at TaleWorlds.CampaignSystem.CampaignPeriodicEventManager.TickPeriodicEvents()
   at TaleWorlds.CampaignSystem.Campaign.Tick()
   at TaleWorlds.CampaignSystem.GameState.MapState.OnMapModeTick(Single dt)
   at TaleWorlds.CampaignSystem.GameState.MapState.OnTick(Single dt)
   at TaleWorlds.Core.GameStateManager.OnTick(Single dt)
   at TaleWorlds.Core.Game.OnTick(Single dt)
   at TaleWorlds.Core.GameManagerBase.OnTick(Single dt)
   at TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch1(Module this, Single dt)

------

**Comment by R-Vaccari** [comment]
`DefaultSettlementValueModel.CalculateSettlementValueForFaction` is crashing, meaning that vanilla code is crashing, not the behavior added by the mod in `BKSettlementValueModel`. It's unlikely the mod is at fault. Try without Serve as Soldier.

**Comment by iEssence** [comment]
That seems to have been the case, deactivated SaS and it worked (sorry, forgot to update it here), no clue why though, since it worked for the other kingdoms but not the one i joined... either way, not a Banner Kings issue (like the error messages said)

**Comment by R-Vaccari** [comment]
It seems to me that SaS introduces a party without leader into the army, hence the crash, as this is otherwise impossible. Thank you.
