### ISSUE TITLE
ErrorLog.TXT Mod works mostly fine.

### ISSUE THREAD

**Issue by LoneMerc** [R-Vaccari/bannerlord-banner-kings#65]
Mod runs with minimal crashes, but no notables in castles, no book sellers, and no estate management. Here is the UNIQUE exceptions that are being thrown, will attach entire ERRORLOG for reasons.

Exception in EstateData class.
   at BannerKings.Managers.Populations.Estates.Estate.CreateNotableEstate(Hero notable, PopulationData data) in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Managers\Populations\Estates\Estate.cs:line 28
   at BannerKings.Managers.Populations.Estates.EstateData.<>c__DisplayClass15_0.<Update>b__0() in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Managers\Populations\Estates\EstateData.cs:line 153
   at BannerKings.Utils.ExceptionUtils.TryCatch(Action method, String className, Boolean notifty) in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Utils\ExceptionUtils.cs:line 17

Exception in BKGentryBehavior class.
   at TaleWorlds.CampaignSystem.CampaignBehaviors.DisbandPartyCampaignBehavior.OnPartyDisbanded(MobileParty disbandParty, Settlement relatedSettlement)
   at TaleWorlds.CampaignSystem.MbEvent`2.InvokeList(EventHandlerRec`2 list, T1 t1, T2 t2)
   at TaleWorlds.CampaignSystem.CampaignEvents.OnPartyDisbanded(MobileParty disbandParty, Settlement relatedSettlement)
   at TaleWorlds.CampaignSystem.CampaignEventDispatcher.OnPartyDisbanded(MobileParty disbandParty, Settlement relatedSettlement)
   at TaleWorlds.CampaignSystem.Actions.DestroyPartyAction.ApplyForDisbanding(MobileParty disbandedParty, Settlement relatedSettlement)
   at BannerKings.Behaviours.BKGentryBehavior.FinishParty(WarPartyComponent party, Estate estate) in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Behaviours\BKGentryBehavior.cs:line 94
   at BannerKings.Behaviours.BKGentryBehavior.<>c__DisplayClass4_0.<OnClanDailyTick>b__0() in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Behaviours\BKGentryBehavior.cs:line 79
   at BannerKings.Utils.ExceptionUtils.TryCatch(Action method, String className, Boolean notifty) in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Utils\ExceptionUtils.cs:line 17
Exception in BKGentryBehavior class.
   at TaleWorlds.CampaignSystem.CampaignBehaviors.DisbandPartyCampaignBehavior.OnPartyDisbanded(MobileParty disbandParty, Settlement relatedSettlement)
   at TaleWorlds.CampaignSystem.MbEvent`2.InvokeList(EventHandlerRec`2 list, T1 t1, T2 t2)
   at TaleWorlds.CampaignSystem.CampaignEvents.OnPartyDisbanded(MobileParty disbandParty, Settlement relatedSettlement)
   at TaleWorlds.CampaignSystem.CampaignEventDispatcher.OnPartyDisbanded(MobileParty disbandParty, Settlement relatedSettlement)
   at TaleWorlds.CampaignSystem.Actions.DestroyPartyAction.ApplyForDisbanding(MobileParty disbandedParty, Settlement relatedSettlement)
   at BannerKings.Behaviours.BKGentryBehavior.FinishParty(WarPartyComponent party, Estate estate) in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Behaviours\BKGentryBehavior.cs:line 94
   at BannerKings.Behaviours.BKGentryBehavior.<>c__DisplayClass4_0.<OnClanDailyTick>b__0() in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Behaviours\BKGentryBehavior.cs:line 79
   at BannerKings.Utils.ExceptionUtils.TryCatch(Action method, String className, Boolean notifty) in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Utils\ExceptionUtils.cs:line 17
Exception in BKGentryBehavior class.
   at TaleWorlds.CampaignSystem.CampaignBehaviors.DisbandPartyCampaignBehavior.OnPartyDisbanded(MobileParty disbandParty, Settlement relatedSettlement)
   at TaleWorlds.CampaignSystem.MbEvent`2.InvokeList(EventHandlerRec`2 list, T1 t1, T2 t2)
   at TaleWorlds.CampaignSystem.CampaignEvents.OnPartyDisbanded(MobileParty disbandParty, Settlement relatedSettlement)
   at TaleWorlds.CampaignSystem.CampaignEventDispatcher.OnPartyDisbanded(MobileParty disbandParty, Settlement relatedSettlement)
   at TaleWorlds.CampaignSystem.Actions.DestroyPartyAction.ApplyForDisbanding(MobileParty disbandedParty, Settlement relatedSettlement)
   at BannerKings.Behaviours.BKGentryBehavior.FinishParty(WarPartyComponent party, Estate estate) in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Behaviours\BKGentryBehavior.cs:line 94
   at BannerKings.Behaviours.BKGentryBehavior.<>c__DisplayClass4_0.<OnClanDailyTick>b__0() in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Behaviours\BKGentryBehavior.cs:line 79
   at BannerKings.Utils.ExceptionUtils.TryCatch(Action method, String className, Boolean notifty) in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Utils\ExceptionUtils.cs:line 17
Exception in BKGentryBehavior class.
   at TaleWorlds.CampaignSystem.CampaignBehaviors.DisbandPartyCampaignBehavior.OnPartyDisbanded(MobileParty disbandParty, Settlement relatedSettlement)
   at TaleWorlds.CampaignSystem.MbEvent`2.InvokeList(EventHandlerRec`2 list, T1 t1, T2 t2)
   at TaleWorlds.CampaignSystem.CampaignEvents.OnPartyDisbanded(MobileParty disbandParty, Settlement relatedSettlement)
   at TaleWorlds.CampaignSystem.CampaignEventDispatcher.OnPartyDisbanded(MobileParty disbandParty, Settlement relatedSettlement)
   at TaleWorlds.CampaignSystem.Actions.DestroyPartyAction.ApplyForDisbanding(MobileParty disbandedParty, Settlement relatedSettlement)
   at BannerKings.Behaviours.BKGentryBehavior.FinishParty(WarPartyComponent party, Estate estate) in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Behaviours\BKGentryBehavior.cs:line 94
   at BannerKings.Behaviours.BKGentryBehavior.<>c__DisplayClass4_0.<OnClanDailyTick>b__0() in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Behaviours\BKGentryBehavior.cs:line 79
   at BannerKings.Utils.ExceptionUtils.TryCatch(Action method, String className, Boolean notifty) in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Utils\ExceptionUtils.cs:line 17
Exception in BKGentryBehavior class.
   at TaleWorlds.CampaignSystem.CampaignBehaviors.DisbandPartyCampaignBehavior.OnPartyDisbanded(MobileParty disbandParty, Settlement relatedSettlement)
   at TaleWorlds.CampaignSystem.MbEvent`2.InvokeList(EventHandlerRec`2 list, T1 t1, T2 t2)
   at TaleWorlds.CampaignSystem.CampaignEvents.OnPartyDisbanded(MobileParty disbandParty, Settlement relatedSettlement)
   at TaleWorlds.CampaignSystem.CampaignEventDispatcher.OnPartyDisbanded(MobileParty disbandParty, Settlement relatedSettlement)
   at TaleWorlds.CampaignSystem.Actions.DestroyPartyAction.ApplyForDisbanding(MobileParty disbandedParty, Settlement relatedSettlement)
   at BannerKings.Behaviours.BKGentryBehavior.FinishParty(WarPartyComponent party, Estate estate) in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Behaviours\BKGentryBehavior.cs:line 94
   at BannerKings.Behaviours.BKGentryBehavior.<>c__DisplayClass4_0.<OnClanDailyTick>b__0() in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Behaviours\BKGentryBehavior.cs:line 79
   at BannerKings.Utils.ExceptionUtils.TryCatch(Action method, String className, Boolean notifty) in C:\Users\Rodrigo\source\repos\bannerlord-banner-kings\BannerKings\Utils\ExceptionUtils.cs:line 17
[errorlog.txt](https://github.com/R-Vaccari/bannerlord-banner-kings/files/10369339/errorlog.txt)

**Comment by R-Vaccari** [comment]
I found this to be related to starting a campaign after having loaded another campaign in the same Bannerlord instance. The mod data would be inconsistent. This was fixed for next version 1.2.6.2.
