### ISSUE TITLE
crashes when entering clan screen 

### ISSUE THREAD

**Issue by Taluron** [R-Vaccari/bannerlord-banner-kings#94]
the game crashes the 1st time you enter your clan screen 
**Mod Version**
- Standard 
- Numeric Version: 1.2.7.1

**Evidence**
- [ ] The mod is present in the callstack;
- [ ] The issue only happens with the mod activated;
- [ ] You tested it with the least amount of other mods as possible.
I've tested the it with only banner kings active
**Crash Report**
 at BannerKings.UI.Items.BKItemVM..ctor(Int32 index, Boolean isAvailable, TextObject hint, TextObject name)
   at BannerKings.UI.Court.CouncilPositionVM..ctor(CouncilMember position, Action`1 setId, Action`1 updatePosition)
   at BannerKings.UI.Court.CourtVM.RefreshValues()
   at BannerKings.UI.Extensions.ClanManagementMixin.OnRefresh()
   at Bannerlord.UIExtenderEx.Patches.ViewModelWithMixinPatch.Constructor(ViewModel viewModel, String _)
   at TaleWorlds.CampaignSystem.ViewModelCollection.ClanManagement.ClanManagementVM..ctor_Patch0(ClanManagementVM this, Action onClose, Action`1 showHeroOnMap, Action`1 openPartyAsManage, Action openBannerEditor)
   at SandBox.GauntletUI.GauntletClanScreen.TaleWorlds.Core.IGameStateListener.OnActivate()
   at TaleWorlds.Core.GameState.HandleActivate()
   at TaleWorlds.Core.GameStateManager.OnPushState(GameState gameState)
   at TaleWorlds.Core.GameStateManager.DoGameStateJobs()
   at TaleWorlds.Core.GameStateManager.PushState(GameState gameState, Int32 level)
   at SandBox.View.Map.MapNavigationHandler.PrepareToOpenClanScreen(Action openClanScreenAction)Outer exception callstack: 
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at TaleWorlds.Library.Common.InvokeWithLog(MethodInfo methodInfo, Object obj, Object[] args)
   at TaleWorlds.Library.ViewModel.ExecuteCommand_Patch1(ViewModel this, String commandName, Object[] parameters)
   at TaleWorlds.GauntletUI.Data.GauntletView.OnCommand(String command, Object[] args)
   at TaleWorlds.GauntletUI.BaseTypes.Widget.EventFired(String eventName, Object[] args)
   at TaleWorlds.GauntletUI.BaseTypes.ButtonWidget.HandleClick()
   at TaleWorlds.GauntletUI.BaseTypes.ButtonWidget.OnMouseReleased()
   at TaleWorlds.GauntletUI.EventManager.MouseUp()
   at TaleWorlds.GauntletUI.UIContext.UpdateInput(InputType handleInputs)
   at TaleWorlds.ScreenSystem.ScreenManager.Update()
   at TaleWorlds.ScreenSystem.ScreenManager.Tick_Patch1(Single dt, Boolean activeMouseVisible)

**Comment by UNOwenWasMe** [comment]
Can confirm this is the case. 
Tried it with only bannerlord and required mods, upon new campaign or sandbox it crashes upon going to clan page.

I have been able to circumvent this by starting a new campaign with the previous version, opening the clan page, then saving, then swapping with the new version. Upon loading the save with the updated bannerlord it does not crash. Will report if it happens in the future again.

**Comment by illutian** [comment]
> Can confirm this is the case. Tried it with only bannerlord and required mods, upon new campaign or sandbox it crashes upon going to clan page.
> 
> I have been able to circumvent this by starting a new campaign with the previous version, opening the clan page, then saving, then swapping with the new version. Upon loading the save with the updated bannerlord it does not crash. Will report if it happens in the future again.

Sounds like an initialization problem. Like in the new version it's calling for something it hasn't generated yet and flakes out because of it.

**Comment by Stevo-Keyz** [comment]
> Can confirm this is the case. Tried it with only bannerlord and required mods, upon new campaign or sandbox it crashes upon going to clan page.
> 
> I have been able to circumvent this by starting a new campaign with the previous version, opening the clan page, then saving, then swapping with the new version. Upon loading the save with the updated bannerlord it does not crash. Will report if it happens in the future again.

So do you mean game version or the BannerKing Version , thank you

**Comment by UNOwenWasMe** [comment]
> 

I mean the Banner Kings version, going from 1.2.7 to 1.2.7.1

**Comment by Stevo-Keyz** [comment]
> > So do you mean game version or the BannerKing Version , thank you
> 
> I mean the Banner Kings version, going from 1.2.7 to 1.2.7.1

Okay thank you I shall do the same is everything still running smooth for you?

**Comment by UNOwenWasMe** [comment]
> > > So do you mean game version or the BannerKing Version , thank you
> > 
> > 
> > I mean the Banner Kings version, going from 1.2.7 to 1.2.7.1
> 
> Okay thank you I shall do the same is everything still running smooth for you?

Yup, haven't had any problems, joined a kingdom and everything is going without any issue.
